### ISSUE TITLE
バトランレビュー

### ISSUE THREAD

**Issue by hisaju** [tsubasahirakida/tun_ari_app#156]
遅くなってしまい申し訳ございません。。
※ 確認後closeしてください

## サービスレビュー

* テーマが面白いので、方向感としてはこのままでうまく拡張してもらえたらと思います。
* 今のままだと投稿 + 画像生成で終わっちゃうので、次のステップとして何が出来るかを考えてみていただけたらいいのかなと思いました。
* ちなみにChatGPTでもツンデレ口調は使えたので、この辺り使っても面白いかもです。
[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/d93f729fb67653ec50f7d32765f1f702.png)](https://startup-technology.gyazo.com/d93f729fb67653ec50f7d32765f1f702)

## コードレビュー

https://github.com/tsubasahirakida/tun_ari_app/blob/c8f2b7810948dd281da48ac191c76479027562f9/app/controllers/posts_controller.rb#L99-L105

enumを使う場合は文字列を使い、マジックナンバーは避けたほうがいいですね
```
@post.status = if params[:commit] == '下書きにする'
                     :draft
                   elsif params[:commit] == '非公開にする'
                     :archive
                   else
                     :publish
                   end
```

* カードを作るモジュールをconcernで定義していたり、ポリモーフィック関連を適切に使われていたので、しっかりと理解されているように思えました。それぞれのActionのコントローラは分けないでうまく共通化出来るといいかなと思いました。
* 上記と同様にUserモデルのメソッドが多くなってるので、すべてメソッド化せずにactionのシンボル渡すことで適切なモデルに追加するような処理にするように出来たらと思います。
* 上記読んでいただき、できそうなところをリファクタしてもらったらsystem specを追加すれば就活はいけるんじゃないかなと思います。やってみて技術的に突っ込まれるようであれば追加の機能もご検討ください。

**Comment by tsubasahirakida** [comment]
レビューありがとうございます😆
・Chatgpt思ったより安いので、将来的に入れていきたいです！
・マジックナンバーの単語を始めて知りました。確かに見ても自分しか分からないので、修正します！
・Action関連の処理の共通化を、なぜシンボルを渡すことで可能なのか分かりませんでしたが、全体のコード像は理解できました！
細かい部分まで見ていただいてありがとうございます！！頑張ります！
